name: build top
on: [push, workflow_dispatch]
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                workflow: verilator.yml
                name: verilator-archive
            - name: Decompress artifact
              run: |
                tar --extract --gzip --file="verilator-archive"
            - name: Check Verilator version
              run: |
                ./verilator/bin/verilator --version
            - name: Build
              run: |
                ls -l
                ./verilator/bin/verilator -I="./verilator/include" -cc --exe top.v sim_main.cpp
                make -j -C obj_dir -f Vtop.mk

