name: build top
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                sudo apt-get update
                sudo apt-get install iverilog
                iverilog -o top top.v
                vvp top
