name: build top
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: test.py
            - name: Run script
              run: |
                python3 test.py
