name: Build and run simulation
on: [push, workflow_dispatch]
env:
    VERILATOR_ROOT: /home/runner/work/verilated-gcd/verilated-gcd/verilator
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install ccache mold
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                workflow: verilator.yml
                name: verilator-archive
            - name: Decompress artifact
              run: |
                echo "$PWD"  
                tar --extract --gzip --file="verilator-archive"
            - name: Check Verilator version
              run: |
                echo "$PWD"  
                ./verilator/bin/verilator --version  
            - name: Configure Verilator environment variables
              run: |
                echo "$PWD"
                echo "$VERILATOR_ROOT/bin" >> $GITHUB_PATH
                echo "$PATH"
            - name: Check Verilator version again
              run: |
                echo "$PWD"
                echo "$PATH"
                verilator --version
            - name: Generate testcases
              run: |
                echo "$PWD"
                python3 create_testcases.py
            - name: Build 1
              run: |
                echo "$PWD"
                echo "$VERILATOR_ROOT"
                verilator -cc --exe top.v sim_main.cpp
            - name: Build 2
              run: |
                echo "$PWD"
                echo "$VERILATOR_ROOT"
                make -j -C obj_dir -f Vtop.mk
            - name: Run
              run: |
                ./obj_dir/Vtop
