name: build top
on: [push, workflow_dispatch]
env:
    VERILATOR_ROOT: ./verilator
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                workflow: verilator.yml
                name: verilator-archive
            - name: Decompress artifact
              run: |
                tar --extract --gzip --file="verilator-archive"
            - name: Check Verilator version
              run: |
                ./verilator/bin/verilator --version  
            - name: Configure Verilator environment variables
              run: |
                echo "$VERILATOR_ROOT/bin" >> $GITHUB_PATH
            - name: Check Verilator version again
              run: |
                verilator --version
            - name: Build
              run: |
                verilator -cc --exe top.v sim_main.cpp
                make -j -C obj_dir -f Vtop.mk

