name: build top
on: [push, workflow_dispatch]
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: verilator-archive
                github-token: ${{ secrets.GITHUB_TOKEN }}
                repository: RHamalainen/verilator-gcd
                run-id: 8143856439
