name: build top
on: [push, workflow_dispatch]
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: dawidd6/action-download-artifact@v3
              with:
                workflow: verilator.yml
                name: verilator-archive
