name: build top
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              run: |
                touch test.py
                echo "print(\"Hello, World!\")" >> test.py
            - name: Cache
              id: cache
              uses: actions/cache@v4
              with:
                path: test.py
                key: hashFiles("test.py")
            - name: Test
              run: |
                python3 test.py
    run:
        runs-on: ubuntu-latest
        steps:
            - name: Restore cache
              id: cache-restore
              uses: actions/cache/restore@v4
              with:
                path: test.py
                key: test.py
            - name: Run script
              run: |
                python3 test.py
