name: Build and cache Verilator
on: workflow_dispatch
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Verilator
              run: |
                touch test.py
                echo "print(\"Hello, World!\")" >> test.py
            - name: Archive artifacts
              uses: actions/upload-artifact@v4
              with:
                name: test.py
                path: test.py

