name: Build and cache Verilator
on: workflow_dispatch
env:
  VERILATOR_ROOT: ./verilator
jobs:
    job:
        runs-on: ubuntu-latest
        steps:
            - name: Install dependencies
              run: |
                echo "$PWD"
                sudo apt-get update
                sudo apt-get install git help2man perl python3 make autoconf g++ flex bison ccache
                sudo apt-get install libunwind-dev libgoogle-perftools-dev numactl perl-doc
                sudo apt-get install libfl2
                sudo apt-get install libfl-dev
            - name: Clone Verilator
              run: |
                echo "$PWD"
                git clone https://github.com/verilator/verilator
                cd verilator
                git pull
                git checkout stable
            - name: Build and install Verilator
              run: |
                cd verilator
                echo "$PWD"
                ls -l
                autoconf
                ./configure
                make --jobs `nproc` --keep-going
            - name: Compress artifacts
              run: |
                echo "$PWD"
                tar --format=posix --create --gzip --file="verilator-archive" verilator
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: verilator-archive
                path: verilator-archive

